### ISSUE TITLE
Finding a vulnerability should result in a non-zero return code

### ISSUE THREAD

**Issue by JonasHess** [jfrog/jfrog-spring-tools#5]
We have wrapped this script in a Jenkins Pipeline. 
Unfortunately the pipeline does not fail if a vulnerable JAR file is actually found. The pipeline stays green, where red would be expected.
 
It would be great you could call sys.exit(1) (or any non-zero integer) if the script finds a vulnerability. This way the entire pipeline could fail.

**Comment by ilya-k-1** [comment]
Hi @JonasHess , 
Added setting exit status in latest commit (exit status = 1 only for cases when a potential vulnerability is found; not set upon corrupted files and other issues)
Thanks!

**Comment by JonasHess** [comment]
@ilya-k-1   thanks,  works like a charm.
